### ISSUE TITLE
Is it possible to get a ping when shot extraction is started and ended from the Micra?

### ISSUE THREAD

**Issue by ilpantera** [zweckj/lmcloud#1]
Thanks for your work on this! Is it possible to get a ping when shot extraction is started and ended from the Micra with this API?
This would be great to integrate it with a scale like the Acaia

**Comment by zweckj** [comment]
Unfortunately no (or at least not yet), that's something I'd like to have as well. I assume that is only happening through the local streaming API. But I still couldn't find out how the local API works...

**Comment by zweckj** [comment]
> This would be great to integrate it with a scale like the Acaia

I looked into it a bit. I found a way to access, the timer but even if I get the timer from the Machine, integrating it with Acaia won't be possible, as they only support mobile SDKs (Android & iOS) for connections.
Not sure where I could display this info in HA so it would still be useful.

**Comment by zweckj** [comment]
> Sounds great! Do you see a lag in when this information is sent or is it near real time? I mean a second doesn't really matter that much but 5 would be critical. On the other hand, the LM App also manages to get the time quite quick (if it works occasionally...) ;-)
The information is as real time as the LM App gets it (and I should theoretically even be able to access it more reliably). I still need to figure out how the apps sends commands to the machine in streaming mode, before I can really implement that though...

> My idea was to combine your code with this one: https://github.com/lucapinello/pyacaia Run it on a Pi Zero or something like that can be connected via bluetooth to the Acaia and then call the scale.startTimer() and scale.stopTimer() from the pyacaia repository
Thanks didn't know this repository. That looks very interesting. Maybe put a webserver around it and call a generic scale HTTP endpoint from the lamarzocco intergration. Will think about it.
