### ISSUE TITLE
[Question] Brew start/stop sent over only localapi?

### ISSUE THREAD

**Issue by jdkuki** [zweckj/lmcloud#37]
Hello,

I have recently purchased a micra (still shipping) and have some resistance on having to keep an app on standby to access settings on the machine. I have been looking into building some basic controls via an ESP32 setup over bluetooth/micropython and found all this great work via the HA forums :). 

I would like to build set/get temp controls which I can follow from their source and yours, however, I would also like to build an automatic shot timer. I see the localapi websocket seems to expose this notification: Would you know if this is also sent over bluetooth? I would like to keep the machine completely off of wifi if possible (or at least their cloud) and not sure if I can also get a local connection without also phoning LM directy.

**Comment by zweckj** [comment]
That information is only available on the WebSocket. You might be able to limit its internet access once you got the local token from either the cloud endpoint or the QR code inside of the machine, but I never tried if the machine accepts that. Also, keep in mind that you will definitely lose functionality that is only available through the cloud (e.g. prebrew/preinfusion/backflush)
